# Generated by Django 5.2.14 on 2026-06-17 03:53
# Modified: 加 RunPython 数据迁移

import ast
from collections import defaultdict

from django.db import migrations, models


# SVID number ranges -> language identifier
SVID_LANG_MAP = [
    (5000, 5999, 'java'),
    (6000, 6999, 'javascript'),
    (7000, 7999, 'python'),
    (8000, 8999, 'go'),
    (9000, 9999, 'c'),
    (10000, 19999, 'php'),
    (1000, 1999, 'php'),
]


def _infer_language(data):
    """Infer language from SVID number ranges in filter_functions and extra_sinks."""
    all_svids = []
    for v in data['filter_functions'].values():
        if isinstance(v, dict) and 'safe_for' in v:
            all_svids.extend(v['safe_for'])
        elif isinstance(v, list):
            all_svids.extend(v)
    for _, svids in data['extra_sinks']:
        if isinstance(svids, list):
            all_svids.extend(svids)
    for svid in all_svids:
        for lo, hi, lang in SVID_LANG_MAP:
            if lo <= svid <= hi:
                return lang
    return 'php'


def _safe_eval(value_str):
    """安全解析字符串形式的 list/dict。解析失败返回原始字符串。"""
    if not value_str:
        return value_str
    try:
        return ast.literal_eval(value_str)
    except (ValueError, SyntaxError):
        return value_str


def migrate_tampers_to_frameworktamper(apps, schema_editor):
    """
    将旧 Tampers 表的扁平结构迁移到新 FrameworkTamper 表。

    旧格式：每行 (tam_name, tam_type, tam_key, tam_value)
    - Filter-Function: {func_name: "[svid_list]"} 或 {func_name: "{'safe_for': [svid_list]}"}
    - Input-Control / Controlled-Sources: 源名
    - Extra-Sinks: (sink_name, [svid_list])

    新格式：一个 tamper 一行，filter_functions/controlled_sources/extra_sinks 为 JSON 字段。
    """
    Tampers = apps.get_model('index', 'Tampers')
    FrameworkTamper = apps.get_model('index', 'FrameworkTamper')

    groups = defaultdict(lambda: {
        'filter_functions': {},
        'extra_sinks': [],
        'controlled_sources': [],
    })

    for t in Tampers.objects.all():
        group = groups[t.tam_name]

        if t.tam_type in ('Filter-Function', 'Filter-function', 'filter_functions', 'filter-function'):
            val = _safe_eval(t.tam_value)
            if isinstance(val, dict):
                group['filter_functions'][t.tam_key] = val
            elif isinstance(val, list):
                group['filter_functions'][t.tam_key] = {'safe_for': val}
            else:
                group['filter_functions'][t.tam_key] = {'safe_for': []}

        elif t.tam_type in ('Input-Control', 'input_control', 'Controlled-Sources', 'controlled_sources'):
            group['controlled_sources'].append(t.tam_value)

        elif t.tam_type in ('Extra-Sinks', 'extra_sinks'):
            val = _safe_eval(t.tam_value)
            if isinstance(val, list):
                group['extra_sinks'].append((t.tam_key, val))

    for name, data in groups.items():
        language = _infer_language(data)
        FrameworkTamper.objects.update_or_create(
            name=name,
            defaults={
                'language': language,
                'framework_name': name,
                'dependencies': {},
                'filter_functions': data['filter_functions'],
                'extra_sinks': data['extra_sinks'],
                'controlled_sources': data['controlled_sources'],
                'detect_code': '',
            }
        )


def reverse_migrate_tampers(apps, schema_editor):
    """反向迁移：从 FrameworkTamper 回到 Tampers（用于 migrate --fake-backward）。"""
    Tampers = apps.get_model('index', 'Tampers')
    FrameworkTamper = apps.get_model('index', 'FrameworkTamper')

    for ft in FrameworkTamper.objects.all():
        for func_name, func_value in (ft.filter_functions or {}).items():
            Tampers.objects.create(
                tam_name=ft.name,
                tam_type='Filter-Function',
                tam_key=func_name,
                tam_value=str(func_value),
            )
        for source in (ft.controlled_sources or []):
            Tampers.objects.create(
                tam_name=ft.name,
                tam_type='Input-Control',
                tam_key=ft.name,
                tam_value=source,
            )
        for item in (ft.extra_sinks or []):
            if isinstance(item, (list, tuple)) and len(item) >= 2:
                Tampers.objects.create(
                    tam_name=ft.name,
                    tam_type='Extra-Sinks',
                    tam_key=item[0],
                    tam_value=str(item[1]),
                )


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_scantask_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkTamper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='框架标识名，如 django, express', max_length=50, unique=True)),
                ('language', models.CharField(help_text='语言，如 python, javascript', max_length=20)),
                ('framework_name', models.CharField(default='', help_text='显示名称，如 Django, Express', max_length=50)),
                ('dependencies', models.JSONField(blank=True, default=dict, help_text='DEPENDENCIES dict')),
                ('filter_functions', models.JSONField(blank=True, default=dict, help_text='FILTER_FUNCTIONS dict')),
                ('extra_sinks', models.JSONField(blank=True, default=list, help_text='EXTRA_SINKS list')),
                ('controlled_sources', models.JSONField(blank=True, default=list, help_text='CONTROLLED_SOURCES list')),
                ('detect_code', models.TextField(blank=True, default='', help_text='detect() 函数源码')),
            ],
            options={
                'verbose_name': 'Framework Tamper',
                'db_table': 'framework_tamper',
            },
        ),
        migrations.RunPython(
            migrate_tampers_to_frameworktamper,
            reverse_migrate_tampers,
        ),
        migrations.DeleteModel(
            name='Tampers',
        ),
    ]
